### ISSUE TITLE
Installer: Non-default Visual Studio IDE Installation Root Directory Issue.

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#522]
Summary: If a user has installed the Visual Studio IDE to a machine that has a non-default root drive letter.  (D:, E:, F:) the plugin install will fail.

Related Task: #637

**Comment by srinivas4912** [comment]
Steps to Reproduce:
1. Installed the Visual Studio IDE to a non-default location on Win7 64 bit.
2. and after Installed VS2013 plugin from build 2.0.0018
3. It's created bbndk_vs folder and installed successful.
4. Open Visual Studio IDE. 

Actual Result: User is unable to find the blackberry menu from IDE.
![image](https://f.cloud.github.com/assets/5992406/2107264/058e5eb6-8fc4-11e3-8031-e743d0dbe9e6.png)

**Comment by zadmarbella** [comment]
This also fails on VS2012.
2.0.0021
Preq: Having vs2012 installed on a D: drive
1 Install the plugin using the installer automatically places it in the D: drive
2 Access Blackberry > Settings

Current Behaviour:
Error window appears and Setting Window doesn't appear
![plugininstalledinanotherdrive](https://f.cloud.github.com/assets/1478549/2127532/0095b950-9270-11e3-8699-eb6d30bf68b2.png)
Note: that previous version 2.0.0018 worked.

**Comment by dbrgss** [comment]
This SHOULD be refixed.   Sorry about sending it back.   It's hard for me to test as I don't have the ability to install Windows on a non-standard drive.

**Comment by dbrgss** [comment]
There was not comment here...   Did this get retested and then sent back??

**Comment by zadmarbella** [comment]
@dbrgss was this fix reverted in the new build 2.0.0022

**Comment by dbrgss** [comment]
This issue should be fixed in version 2.0.0022.   If you uninstall and re-install with the new version... and try again this should work.   This fix ONLY fixes a non-default drive scenario....   IE..  You have installed Windows and then VisualStudio on a D, E, Or other drive letter.   The path after that needs to be standard.. IE XXX:\Program Files (x86)\Microsoft Visual Studio 11.0 where XXX is the different drive letters.

**Comment by dbrgss** [comment]
Updated the issue description to be more specific.   This issue is concerned only when Visual Studio is installed to a non-default root drive.  For example trying to install to a F: drive.   The ability to install to a non-default installation of Visual Studio has been added as a related Task.

**Comment by srinivas4912** [comment]
Windows OS installed on "C" drive.
As per the above comments we have created the following folder structure.
D:\Program Files (x86)\Microsoft Visual Studio 11.0

Installed Visual studio in the above created folder structure

Plugin is installed from the plugin installer. "bbndk_vs" folder is found in "C" drive (C:\bbdnk_vs).

Blackberry menu is not visible from Visual studio IDE.

Is this the correct behavior. Could you please confirm?

**Comment by dbrgss** [comment]
Can you please do the following:

Make sure that Visual Studio is closed.

Browse to the following directory... from a CMD prompt

C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE

Run the following command:

devenv.exe /setup

Rerun Visual Studio...   You should see the BlackBerry menu

**Comment by srinivas4912** [comment]
Run the below command:
devenv.exe /setup and it is executed.
BlackBerry menu is still not visible from Visual Studio IDE.

**Comment by srinivas4912** [comment]
Verification failed using VS2012 plugin from v2.0.0022 on Win7 64 bit.

Followed the below steps to verify the issue:
1. Windows is installed in "C" drive
2. Installed Visual Studio 2012 in "D" drive IE.. D:\Program Files (x86)\Microsoft Visual Studio 11.0 
3. Installed VS2012 plugin and "bbndk_vs" folder is found in "C" drive (C:\bbdnk_vs).
4. Browse to the following directory... from a CMD prompt
D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE
Run the following command: devenv.exe /setup
5. Rerun Visual Studio 

Actual Result:
BlackBerry menu is not visible from Visual Studio IDE.

**Comment by dbrgss** [comment]
Downgraded to a P3 as issue is now considered an edge case.
